#!/bin/sh
# colima-system — wrapper for Colima system daemon on macOS.
# Author: Dmitrii Safronov <dhameoelin@gmail.com>

set -e

sudo -u ${COLIMA_USER} \
    -H \
    env -i \
    HOME=${COLIMA_HOME} \
    PATH=/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin \
    SHELL=/bin/sh \
    ${COLIMA_BIN} \
    $@
